version: 2

build:
  os: ubuntu-lts-latest  # triggering by commit message -- shouldn't trigger
  tools:
    python: latest

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
